// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxpcmxvxhvimincugfwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4cGNteHZ4aHZpbWluY3VnZndsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNDczMDcsImV4cCI6MjA2MzYyMzMwN30.wx-rrWYN4q1TYOdCpkxobn-aydRMiZHzummif2Nu0fQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);